name: Greetings Professor Falken
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20196
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Cameron Hunter Bell '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d22d27'
    - '#fefefe'
    - '#e46e6d'
    - '#c64b4e'
    - '#ffa5ac'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
