name: Greetings Professor Falken
favicon: null
layout_spectrum: 0.01728
typography_spectrum: 0.33232
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Cameron Hunter Bell '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9ff00'
    - '#090c07'
    - '#ff0000'
    - '#75815b'
    - '#0046c5'
  brandStrength: 0
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
