name: Cameron Hunter Bell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6667549984995276
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Cameron Hunter Bell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040104'
    - '#FF01FF'
    - '#FFFEFF'
    - '#995D5C'
    - '#0DFBFF'
  brandStrength: 0.6333737729582936
  lightness: 0.9779807
  saturation: 0.858754
  rhythmicContrast: 0.05746506
purpose: []
