name: Cameron Hunter Bell
favicon: null
layout_spectrum: 0.5247449115850031
typography_spectrum: 0.6667549984995276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6333737729582936
  lightness: 0.6063781108241528
  saturation: 0.35766900586895645
  rhythmicContrast: 0.8001724295318127
purpose: []
